Repository CSC207-2022F-UofT/course-project-uofteams, pull requests merged in 2022-12, with the labels that each got.

#89 Refresh Main View Feature
  src/main/java/filter_post/ui/FilterPostBarView.java
  src/main/java/view_post/ui/MainPostView.java
  src/main/java/view_post/ui/PostListView.java
  src/main/java/view_post/ui/ViewPostView.java
  src/test/java/filter_post/FilterPostTest.java
Labels: enhancement

#161 Update the README.md file
  README.md
Labels: documentation

#157 Fix tests for currentUser and refactor database directory.
  src/main/java/UofTeams.java
  src/main/java/make_post/Main.java
  src/test/java/entities/CurrentUserTest.java
  src/test/java/favourite/FavouriteTest.java
  src/test/java/sign_up/SignUpTest.java
Labels: bug
